import { ColumnName, ElementType } from './types';
import type { GenerateConfigInput } from './jsonGenerator';

/**
 * Example data ported from appsscript/src/devHelpers.ts populateConfig().
 */
export const EXAMPLE_DATA: GenerateConfigInput = {
  timing: [
    {
      [ColumnName.templateVideo]: 'template.mp4',
      [ColumnName.offsetS]: '11',
      [ColumnName.durationS]: '4',
      [ColumnName.placementId]: '1',
    },
    {
      [ColumnName.templateVideo]: 'template.mp4',
      [ColumnName.offsetS]: '15',
      [ColumnName.durationS]: '5',
      [ColumnName.placementId]: '1',
    },
    {
      [ColumnName.templateVideo]: 'template.mp4',
      [ColumnName.offsetS]: '20',
      [ColumnName.durationS]: '4',
      [ColumnName.placementId]: '1',
    },
  ],
  placements: [
    {
      [ColumnName.placementId]: '1',
      [ColumnName.elementId]: 'price_text',
      [ColumnName.elementType]: ElementType.text,
      [ColumnName.dataField]: 'Price',
      [ColumnName.relativeTo]: '',
      [ColumnName.elementHorizontalAnchor]: '',
      [ColumnName.elementVerticalAnchor]: '',
      [ColumnName.relativeHorizontalAnchor]: '',
      [ColumnName.relativeVerticalAnchor]: '',
      [ColumnName.offsetX]: '1050',
      [ColumnName.offsetY]: '280',
      [ColumnName.rotationAngle]: '0',
      [ColumnName.imageWidth]: '',
      [ColumnName.imageHeight]: '',
      [ColumnName.keepRatio]: '',
      [ColumnName.textFont]: '',
      [ColumnName.textSize]: '100',
      [ColumnName.textWidth]: '400',
      [ColumnName.textAlignment]: 'left',
      [ColumnName.textColor]: '#0088ff',
      [ColumnName.removeBackground]: '',
    },
    {
      [ColumnName.placementId]: '1',
      [ColumnName.elementId]: 'product_image',
      [ColumnName.elementType]: ElementType.image,
      [ColumnName.dataField]: 'Image',
      [ColumnName.relativeTo]: '',
      [ColumnName.elementHorizontalAnchor]: '',
      [ColumnName.elementVerticalAnchor]: '',
      [ColumnName.relativeHorizontalAnchor]: '',
      [ColumnName.relativeVerticalAnchor]: '',
      [ColumnName.offsetX]: '750',
      [ColumnName.offsetY]: '600',
      [ColumnName.rotationAngle]: '0',
      [ColumnName.imageWidth]: '1000',
      [ColumnName.imageHeight]: '1000',
      [ColumnName.keepRatio]: '',
      [ColumnName.textFont]: '',
      [ColumnName.textSize]: '',
      [ColumnName.textWidth]: '',
      [ColumnName.textAlignment]: '',
      [ColumnName.textColor]: '',
      [ColumnName.removeBackground]: '',
    },
    {
      [ColumnName.placementId]: '1',
      [ColumnName.elementId]: 'title_text',
      [ColumnName.elementType]: ElementType.text,
      [ColumnName.dataField]: 'Title',
      [ColumnName.relativeTo]: '',
      [ColumnName.elementHorizontalAnchor]: '',
      [ColumnName.elementVerticalAnchor]: '',
      [ColumnName.relativeHorizontalAnchor]: '',
      [ColumnName.relativeVerticalAnchor]: '',
      [ColumnName.offsetX]: '60',
      [ColumnName.offsetY]: '50',
      [ColumnName.rotationAngle]: '0',
      [ColumnName.imageWidth]: '',
      [ColumnName.imageHeight]: '',
      [ColumnName.keepRatio]: '',
      [ColumnName.textFont]: '',
      [ColumnName.textSize]: '120',
      [ColumnName.textWidth]: '400',
      [ColumnName.textAlignment]: 'left',
      [ColumnName.textColor]: '#ff8800',
      [ColumnName.removeBackground]: '',
    },
  ],
  offers: [
    {
      [ColumnName.offerId]: '1001',
      Title: 'Apples',
      Image:
        'https://raw.githubusercontent.com/google/product_video_ads/main/example_assets/apples.png',
      Price: '€1.09',
      [ColumnName.zoomEffect]: 'in',
      [ColumnName.zoomAmount]: '1.3',
    },
    {
      [ColumnName.offerId]: '1002',
      Title: 'Bananas',
      Image:
        'https://raw.githubusercontent.com/google/product_video_ads/main/example_assets/bananas.png',
      Price: '€2.09',
      [ColumnName.zoomEffect]: '',
      [ColumnName.zoomAmount]: '',
    },
    {
      [ColumnName.offerId]: '1003',
      Title: 'Broccoli',
      Image:
        'https://raw.githubusercontent.com/google/product_video_ads/main/example_assets/broccoli.png',
      Price: '€1.59',
      [ColumnName.zoomEffect]: 'out',
      [ColumnName.zoomAmount]: '1.2',
    },
    {
      [ColumnName.offerId]: '1004',
      Title: 'Oranges',
      Image:
        'https://raw.githubusercontent.com/google/product_video_ads/main/example_assets/oranges.png',
      Price: '€1.29',
      [ColumnName.zoomEffect]: 'in',
      [ColumnName.zoomAmount]: '1.3',
    },
  ],
  offersToAdGroups: [
    { [ColumnName.offerId]: '1001', [ColumnName.adGroup]: 'Hamburg' },
    { [ColumnName.offerId]: '1002', [ColumnName.adGroup]: 'Hamburg' },
    { [ColumnName.offerId]: '1003', [ColumnName.adGroup]: 'Hamburg' },
    { [ColumnName.offerId]: '1001', [ColumnName.adGroup]: 'Berlin' },
    { [ColumnName.offerId]: '1002', [ColumnName.adGroup]: 'Berlin' },
    { [ColumnName.offerId]: '1004', [ColumnName.adGroup]: 'Berlin' },
  ],
  adGroups: [
    {
      [ColumnName.adGroup]: 'Hamburg',
      [ColumnName.templateVideo]: 'template.mp4',
      [ColumnName.adGroupType]: 'VIDEO_RESPONSIVE',
      [ColumnName.targetLocation]: '',
      [ColumnName.audienceName]: '',
      [ColumnName.url]: 'https://www.google.de/',
      [ColumnName.callToAction]: 'Zugreifen',
      [ColumnName.headline]: 'Frische Angebote',
      [ColumnName.longHeadline]: 'Frische Angebote Jeden Tag',
      [ColumnName.description1]: 'Lebensmittel, Ersparnisse und mehr.',
      [ColumnName.description2]: '',
    },
    {
      [ColumnName.adGroup]: 'Berlin',
      [ColumnName.templateVideo]: 'template.mp4',
      [ColumnName.adGroupType]: 'VIDEO_RESPONSIVE',
      [ColumnName.targetLocation]: '',
      [ColumnName.audienceName]: '',
      [ColumnName.url]: 'https://www.google.de/',
      [ColumnName.callToAction]: 'Zugreifen',
      [ColumnName.headline]: 'Jetzt Sparen',
      [ColumnName.longHeadline]: 'Supermarkt Angebote der Woche',
      [ColumnName.description1]: 'Riesige Auswahl, kleine Preise.',
      [ColumnName.description2]: '',
    },
  ],
};
